#NODE-PORT

apiVersion: v1
kind: Service
metadata:
  name: python-web-app
spec:
  type: NodePort
  selector:
    app: sample-python-app
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30007


#LOAD-BALANCER

# apiVersion: v1
# kind: Service
# metadata:
#   name: python-web-app
# spec:
#   type: LoadBalancer
#   selector:
#     app: sample-python-app
#   ports:
#     - port: 80
#       targetPort: 8000
#       nodePort: 30007


#DISCOVERY

# apiVersion: v1
# kind: Service
# metadata:
#   name: python-web-app
# spec:
#   type: NodePort
#   selector:
#     app: sample-python-ap
#   ports:
#     - port: 80
#       targetPort: 8000
#       nodePort: 30007